add tolerance style: MORPH1_ONLY, MORPH2_ONLY (with/without opt. morph)
what-studio/tossi pull request #1
Opened 2017-04-01 18:24 UTC by ttti07

tolerance style 옵션을 두 가지 추가해보았습니다.
일단 괄호를 표기하지 않고 싶어서, 어색하더라도 조사 중 하나를 default로 택1할 수 있도록 변경해보았습니다.
```python
>>> import tossi
>>> tossi.postfix_particle(u'さくら', u'이', tolerance_style=tossi.tolerance.MORPH2_ONLY)
さくら가
```

* morph1 vs. morph2 로 나뉘는 케이스 외에, '으로', '이다' 케이스는 다음과 같이 해석했습니다. 적절하지 않다면 말씀해주세요. :)
  - MORPH1_ONLY: with optional morph (longest)
  - MORPH2_ONLY: without optional morph (shortest)
* 수정하게 되는 변수/함수의 참조 범위를 다 체크하고 test.py의 모든 함수를 돌려보긴 했는데, 부작용이 없다고 95% 까지 밖에는 확신을 못 하겠네요 ㅠ
  - 일단 `generate_tolerance` 함수가 6개의 tolerance를 모두 생성해내도록 변경한게 가장 큰 것 같습니다.
* 이 내용이 원래 프로젝트가 추구하던 방향과 맞지 않는다든지 하다면, 더 나은 방안을 함께 논의해보고 이 PR을 drop하거나 수정해보도록 하겠습니다.

2017-04-02 07:32 UTC, sublee commented
한 가지 표기만 쓰는 관용표기는 생각하지 못 했네요. 좋은 제안입니다.

2017-04-03 12:13 UTC, sublee commented
PEP8 오류가 생겼는데 함께 잡아주세요.

2017-06-15 07:26 UTC, ttti07 commented
@sublee 리뷰 및 merge는 어떻게 하면 될까요?
우선 pep8 오류는 잡아보았고, coverity check는 통과하도록 해보았습니다.
(pep8은 자동 fix tool을 이용해볼까요?)

2017-06-15 10:23 UTC, sublee commented
@ttti07 리뷰 마쳤습니다. 다음 코멘트를 확인해주세요:

- https://github.com/what-studio/tossi/pull/1/files/6ccf25cf1df9b8321b960ae83e6321215646eae8#diff-b284a28710cce90d9d9be3a7f4cabc8eR341
- https://github.com/what-studio/tossi/pull/1/files/6ccf25cf1df9b8321b960ae83e6321215646eae8#diff-1d306b9dc26616c56ca54ab73eb2d699R24

2017-06-15 10:27 UTC, sublee requested changes
@ttti07 아래 리뷰 내용을 확인해주세요.

2017-06-15 10:27 UTC, sublee commented on test.py
> +    parse_tolerance_style(u'(이)') == MORPH1_AND_OPTIONAL_MORPH2
의미 있는 줄이 될 수 있도록 `assert`를 추가해주세요:

```python
assert parse_tolerance_style(u'(이)') == MORPH1_AND_OPTIONAL_MORPH2
```

2017-06-15 10:27 UTC, sublee commented on tossi/tolerance.py
> +MORPH1_ONLY = 4  # with optional morph: 은, 으로, 이
`OPTIONAL_MORPH`는 `(는)` 같은 괄호표기를 지칭한 것이라서 `with optional morph`, `without optional morph`는 적절한 설명이 아닙니다. 위에 처럼 예시만 들어줘도 될 것 같아요.

2017-06-15 10:29 UTC, sublee commented
@ttti07 사과 드릴 게 있습니다. GitHub 리뷰 도구를 잘 이해하지 못 해서 이전에 작성한 리뷰 코멘트를 제대로 등록하지 못 했던 것 같습니다. 저에게만 보이는 상태였던 것 같아요. 리뷰가 지연되게 만들어 죄송합니다.

2017-06-18 04:38 UTC, merged

2017-06-18 04:54 UTC, sublee commented
`tolerance` 브랜치에서 정리하고 있었으나 `이었다` 케이스를 의도대로 동작시키기 어려울
 것 같습니다: https://github.com/what-studio/tossi/commit/29c1aafe42ebb475009fa0d3fcf0f5ae32b55b97

혹시 스타일을 추가하는 대신 #3 에서 새로 생긴 인터페이스를 이용할 순 없을까요?

2017-06-18 05:05 UTC, sublee commented
`guess_coda`를 이용하는 것은 어떨까요?

```python
def my_guess_coda(word):
    coda = DEFAULT_GUESS_CODA(word)
    return u'' if coda is None else coda
```

```python
>>> print tossi.postfix_particle(u'벚꽃', u'이', guess_coda=my_guess_coda)
벚꽃이
>>> print tossi.postfix_particle(u'사쿠라', u'이', guess_coda=my_guess_coda)
사쿠라가
>>> print tossi.postfix_particle(u'さくら', u'이', guess_coda=my_guess_coda)
さくら가
```