사용자 정의 tolerance_style
what-studio/tossi pull request #4
Opened 2017-06-16 06:18 UTC by youknowone

tolerance_style에 문자열을 직접 지정할 수 있도록 기능을 추가합니다.

```
postfix_particle(u'나오', u'을', tolerance_style=u'을/를') == u'나오를'
postfix_particle(u'키홀', u'를', tolerance_style=u'을/를') == u'키홀을'
postfix_particle(u'Tossi', u'을', tolerance_style=u'을/를') == u'Tossi을/를'
```

2017-06-16 06:23 UTC, sublee commented
Python 2.7 오류를 잡아주세요: https://travis-ci.org/what-studio/tossi/jobs/243548373

2017-06-16 06:25 UTC, sublee requested changes

2017-06-16 06:25 UTC, sublee commented on tossi/particles.py
> +        elif isinstance(tolerance_style, str):
`str` 대신 `six.text_type`을 써서 Python 2.x와 3.x를 동시에 지원할 수 있게 해주세요.

2017-06-16 06:48 UTC, sublee requested changes

2017-06-16 06:48 UTC, sublee commented on tossi/particles.py
> +        elif isinstance(tolerance_style, string_types):
기존 코드베이스에서 `bytes`는 허용하지 않고 있습니다. `six.string_types` 대신 `six.text_type`을 써주세요.

2017-06-16 06:49 UTC, sublee commented
`import` 순서 오류를 고쳐주세요: https://travis-ci.org/what-studio/tossi/jobs/243551038#L294

2017-06-16 06:57 UTC, youknowone commented
@sublee 모두 수정했습니다 다시 확인 부탁드려요

2017-06-16 07:04 UTC, merged

2017-06-16 07:04 UTC, sublee commented
머지했습니다. 훌륭하군요.

2017-06-18 04:56 UTC, sublee commented
[v0.2.2](https://github.com/what-studio/tossi/releases/tag/v0.2.2)로 PyPI에 배포됐습니다.

2017-06-18 06:42 UTC, youknowone commented
감사합니다 😄